### ISSUE TITLE
Empty page on all applicants routes on production

### ISSUE THREAD

**Issue by amitbend** [forms-angular/forms-angular#82]
I created a new app, worked great and on localhost,
deployed to openshift, and now all applicant routes are not working.

you can test it yourself on the link below (i left simple auth available)
[http://noderform-paladinint.rhcloud.com/](http://noderform-paladinint.rhcloud.com/)

**Comment by mchapman** [comment]
Hi

Thanks for your interest in forms-angular, and for getting in touch.

I'm afraid I have no knowledge of Openshift.  I clicked on the link and it looks like the bits of angular-fullstack template that rely on MongoDB are also not working, so I suggest you start looking there.

If you want to take this any further (and by that I pretty much mean submit a PR, since I don't have time to look into OpenShift at the moment) please could you do it on the https://github.com/forms-angular/generator-angular-fullstack repo?

Mark
